### PR TITLE
Weighted lru 2

### PR DESCRIPTION
**Pull request by maurolacy**
Continues the work started in #24.

- Adds a `max_weight` parameter, so that cache can be used as a memory/size-limited cache (see this [#24 comment](https://github.com/marmeladema/clru-rs/pull/24#discussion_r528249500)).
- Removes `NonZeroUsize` for simplicity and usability, and replaces it by a non-zero check.
- Adds weighted cache unit tests.
- Adds `thiserror`-based error messages.

Setting the base branch to `main` for simplicity. Feel free to change it to `weighted-lru` if you want to compare against it, and / or merge there and continue working on top of it.

### CODE REVIEW

**Comment by marmeladema** [comment]
Thank you for the work! I'll try to take a look soon but I have a lot on my plate right now.

**Comment by marmeladema** [comment]
I am making progress toward this :+1: 
The API won't look exactly like what I had originally drafted and what's in this PR but should nevertheless be suitable for your use cases.

**Comment by marmeladema** [comment]
Superseded by https://github.com/marmeladema/clru-rs/pull/32

Thanks a lot for this @maurolacy ! Especially for all the tests! It has helped me a lot :+1:

**Comment by maurolacy** [comment]
You're welcome. Thanks for the new functionality!

**Pull request closed without merging**
