### PR TITLE
Manually implement `Sync` trait for `CLruCache`

### LINKED ISSUE #43: Add `Sync` version
Hey, I was interested in using this crate in one of projects, however I need `CLruCache` to be `Sync`, as I want to share the cache between threads. Would you be willing to either changing to be using `Arc` internally or providing a `sync` version of `CLruCache`?

### PR DESCRIPTION
**Pull request by marmeladema**
cc @xfix and @XAMPPRocky

Fixes #43

### CODE REVIEW

**Comment by marmeladema** [comment]
@XAMPPRocky any thoughts about this?

**Comment by XAMPPRocky** [comment]
I don't really have any opinion as I'm not familiar with the code, but it looks fine to me.

**Comment by marmeladema** [comment]
Thanks. Will tag a release later today.

**Comment by ShadowJonathan** [comment]
@marmeladema did you forget to cut that release? I just discovered i'd potentially need this.

Edit: Actually, i realised that we use mutexes, so we may not need this specifically, but i'd appreciate it if something like this were to be put in an official release

**Pull request merged**
